### ISSUE TITLE
Fehlermelung TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by CKMartens** [twonky4/ioBroker.spotify-premium#40]
Ich bekomme folgende Fehlermeldung nach starten des Skripts:
```
`javascript.0	2018-11-23 21:09:45.081	error	at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
javascript.0	2018-11-23 21:09:45.081	error	at Request.emit (events.js:211:7)
javascript.0	2018-11-23 21:09:45.081	error	at emitOne (events.js:116:13)
javascript.0	2018-11-23 21:09:45.081	error	at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
javascript.0	2018-11-23 21:09:45.081	error	at Request.emit (events.js:214:7)
javascript.0	2018-11-23 21:09:45.081	error	at emitTwo (events.js:126:13)
javascript.0	2018-11-23 21:09:45.081	error	at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
javascript.0	2018-11-23 21:09:45.081	error	at Request._callback (script.js.Media.Spotify:179:24)
javascript.0	2018-11-23 21:09:45.081	error	at script.js.Media.Spotify:775:31
javascript.0	2018-11-23 21:09:45.081	error	at CreatePlaybackInfo (script.js.Media.Spotify:252:13)
javascript.0	2018-11-23 21:09:45.081	error	TypeError: Cannot read property 'hasOwnProperty' of null
javascript.0	2018-11-23 21:09:45.081	error	uncaught exception: Cannot read property 'hasOwnProperty' of null`
```
Ich benutze die Version 0.5.3 des Scripts und der Token wurde erfolgreich geholt.

**Comment by CKMartens** [comment]
Der Fehler tritt auf wenn kein Device Spotify abspielt. Kann der Fehler irgendwie abgefangen werden?

**Comment by twonky4** [comment]
Hier wird kein Support für das Skript übernommen. Das Skript wird auch nicht weiter entwickelt. Bitte benutze den Adapter.
