### ISSUE TITLE
Regular Error 404

### ISSUE THREAD

**Issue by cburghardt** [twonky4/ioBroker.spotify-premium#60]
The adapter is correctly up and running and I can use it for playback.
What I have noticed is that I regularly get an error 404 in the logs. So apparently an incorrect API call is started. Can I help to debug that?

**Comment by cburghardt** [comment]
More information: the error happens here:
    at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21)
    at Timeout.pollStatusApi [as _onTimeout] (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1469:12)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5

The status call fails. According to this thread the problem is when no device is active:
https://stackoverflow.com/questions/52268847/react-node-spotify-api-error-404-no-active-device-found

**Comment by cburghardt** [comment]
Suggestion to @twonky4 : remove the catch part of sendRequest. This way the error bubbles up and the polling stops.

**Comment by t6a** [comment]
(Speaker: 2 Google Home Mini)
Ive the same problem. After an inactive period, none of the devices are available and none of the buttons work. I can't trigger anything.

**Comment by Azathoth88** [comment]
Bei mir existieren drei Alexas im Haus. Das Problem tritt bei mir regelmäßig auf, wenn ich einige Zeit nicht gehört habe. Ich klicke in meiner vis auf Play und erhalte eine 404, obwohl augenscheinlich ein Player ausgewählt ist. Es wird hier allerdings kein Ton abgespielt. Das Abspielen funktioniert allerdings, wenn ich denselben Player erneut auswähle und auf Play klicke.

Wie mir scheint, wird der aktuelle Player nicht korrekt erkannt bzw. muss reaktiviert werden.

**Comment by EvoXtheAnonym** [comment]
Similar Problem, Adapter is working Fine, i only get the error below in periodic time distance:

`

2020-06-24 11:12:25.583  - warn: spotify-premium.0 (1030) http request error not handled, please debug
--
2020-06-24 11:12:25.588  - warn: spotify-premium.0 (1030) Error
at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21)
at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:961:12)
at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:823:20
at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
at /opt/iobroker/node_modules/promise/lib/core.js:123:15
at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-06-24 11:12:25.589  - warn: spotify-premium.0 (1030) Error
at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:262:38
at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
at /opt/iobroker/node_modules/promise/lib/core.js:123:15
at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-06-24 11:12:25.590  - error: spotify-premium.0 (1030) erron in request: 504
2020-06-24 11:12:25.590  - warn: spotify-premium.0 (1030) error on load tracks: TypeError: Cannot read property 'forEach' of undefined

`

**Comment by cru8602** [comment]
I got the same errorwhen I select a playlist to be played or try to select a device to be played on. so basicly the adapter isn't working at all. 
Is there any chance that this will be fixed soon?
